build: fix codecov action issue
codecov action started erroring 
Run codecov/codecov-action@v1.0.6
/home/runner/work/_actions/codecov/codecov-action/v1.0.6/dist/index.js:20817
      throw error;
      ^

Error: connect ETIMEDOUT 35.199.43.247:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1129:14) {
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT',
  syscall: 'connect',
  address: '35.199.43.247',
  port: 443
}

Let's see if update to latest will fix it.